### ISSUE TITLE
App crash when setting new wallpaper

### ISSUE THREAD

**Issue by ghost** [danielgimenes/NasaPic#2]
When I set a new wallpaper the app crash but still set the new wallpaper.
With the version 2.0 and 2.1 on an alcatel one touch pop 2 with android 4.4.4

**Comment by DamnFinn** [comment]
is that still an issue with the current version?

**Comment by ghost** [comment]
Yes, but the app still works so it's okay I guess ^^

**Comment by DamnFinn** [comment]
ty

**Comment by danielgimenes** [comment]
Hello, guys. Sorry for not responding to this earlier.

Thanks for using the app. I've just released v3.1 in case you want to check it out.

**Comment by ghost** [comment]
Great, waiting for it to be on F-Droid to test it :)

**Comment by DamnFinn** [comment]
yes, i'm also waiting for update on f-droid ;)
