### ISSUE TITLE
Missing WallpaperChangeNotification

### ISSUE THREAD

**Issue by DamnFinn** [danielgimenes/NasaPic#5]
Hey, i tried to run the project on my computer (Android Studio 1.4.1, gradle 1.3.0) for fixing bugs.
but it doesn't work:
error: Cannot find symbol WallpaperChangeNotification... (located in br.com.dgimenes.nasapic.service)

Please fix it. Thank you.

**Comment by DamnFinn** [comment]
Project should be fixed.
File and class can be found in: https://github.com/danielgimenes/NasaPic/tree/master/app/src/main/java/br/com/dgimenes/nasapic/service

**Comment by danielgimenes** [comment]
Hello,

sorry for not doing it earlier.

The app is ok now. I've just released a new version of it at the Play Store.

Thanks for reporting the issue.

**Comment by DamnFinn** [comment]
Thank you, but why is this project dead?
