### ISSUE TITLE
Error accessing nasa api

### ISSUE THREAD

**Issue by adolfintel** [danielgimenes/NasaPic#8]
Doesn't work here.
I'm using a moto g 2015, from italy, didn't touch the permissions, no firewall or anything.
I know github issues are not for this but I didn't see any other way to contact you.

**Comment by StupeFat** [comment]
Same here on Oneplus One, latest Cyanogen Mod, Italy. Installed yesterday from f-droid. See attachment:

![photo](https://cloud.githubusercontent.com/assets/12232896/12608741/1f63c140-c4de-11e5-9917-bb1315f1842e.jpg)

**Comment by StupeFat** [comment]
Update: vers. 3.1.1 is working! thanks

**Comment by adolfintel** [comment]
Nope, it says "Error loading feed (page 1)"
Also, a minor thing. The menu has black text on dark blue background, it's unreadable

**Comment by danielgimenes** [comment]
Hey, guys! Thanks for checking out the app.

I'm currently not supporting F-Droid specifically because they do not allow apps that collect crash reports using Crashlytics. So, please, use the latest version (3.1.1) published at Google Play (https://play.google.com/store/apps/details?id=br.com.dgimenes.nasapic)

adolfintel, about the menu text in black, thanks for the feedback. I'll add it to the backlog.

**Comment by adolfintel** [comment]
You shouldn't use nonfree crashlytics :P

**Comment by danielgimenes** [comment]
It's complicated to develop for Android and not receive crash reports. :(
I need to know if the app is working in other devices/android version, and if not, I want as much info as I can get about the issue (Crashlytics gives me a lot of info about the device and the error that happened, like the error stack trace).

If there was an open-source alternative, I'd use it.

**Comment by StupeFat** [comment]
i just installed it also from Play Store and it woks good too, even if it is a bit slower.

**Comment by adolfintel** [comment]
You should remove it from the f-droid repos if you're not going to fix that version, though

**Comment by danielgimenes** [comment]
I've just checked they're website, and the app is not there anymore.

BTW, I didn't know my app was in F-Droid until last week... haha
