### ISSUE TITLE
Add option to hide "undo-notification" 

### ISSUE THREAD

**Issue by vanitasvitae** [danielgimenes/NasaPic#9]
Hi
I'd like to have an option that disabled the notification that pops up when the app changed the wallpaper.

**Comment by danielgimenes** [comment]
Hi, Vanitasvitae,

If you go to Menu (the three dots) > Settings, you can uncheck "Show notification with undo option" to have exactly that.

**Comment by vanitasvitae** [comment]
Oh man I was blind... Thank you :)
